### PR TITLE
Create 2048_Game.py

### PR DESCRIPTION
**Pull request by GouravSingh2580**
2048 Game in Python

### CODE REVIEW

**Review by SyedZawwarAhmed — COMMENTED** [review]
Put this file in a folder.

**Comment by GouravSingh2580** [comment]
@SyedZawwarAhmed done

**Review by SyedZawwarAhmed — COMMENTED** [review]
Buddy, I told you to remove the whitespace not replace it with underscore. Now, remove the underscore.

**Comment by GouravSingh2580** [comment]
@SyedZawwarAhmed done brother

**Pull request merged**
