### PR TITLE
Added a program to calculate roots of a quadratic equation

### PR DESCRIPTION
**Pull request by karanchoudhxry**

### CODE REVIEW

**Review by SyedZawwarAhmed — COMMENTED** [review]
Move this file to Algorithms/Python folder.
If you can't find the Algorithms folder, sync the main repository with your forked repository.

**Comment by karanchoudhxry** [comment]
Can you please check it again? This file is already in the Algorithms/Python folder

**Comment by SyedZawwarAhmed** [comment]
> 

No, it's in algorithms/python.
Note the capitalization of folder names.

**Comment by SyedZawwarAhmed** [comment]
> > 
> 
> No, it's in algorithms/python. Note the capitalization of folder names.

And also change the filename format to camelCase.

**Comment by karanchoudhxry** [comment]
Hey! Is it ok now?

**Comment by SyedZawwarAhmed** [comment]
> Hey! Is it ok now?

Yes, it is okay now. Nice work, and thanks for the contribution.
Make sure to give me a follow on github.

**Pull request merged**
