### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SyarifulMsth**
Hello 
Hacktoberfest2022 
Thanks a lot!

### CODE REVIEW

**Comment by SyarifulMsth** [comment]
This is simple web project (Popular Webdev Technologies) using HTML and CSS

**Review by SyedZawwarAhmed — COMMENTED** [review]
Name the folder according to the guidlines.

**Comment by SyarifulMsth** [comment]
Done.

**Comment by SyarifulMsth** [comment]
Simple Web Project using HTML CSS
Make Popular Webdev Technologies
Thanks!

**Pull request merged**
