### PR TITLE
Vipuls branch

### PR DESCRIPTION
**Pull request by vipul-vaishnav**
### Linked List implementation using Java in Algorithms

### CODE REVIEW

**Review by SyedZawwarAhmed — COMMENTED** [review]
Start the file names with small letters.

**Comment by SyedZawwarAhmed** [comment]
Put data structure related code in DataStructures folder.

**Comment by vipul-vaishnav** [comment]
## Remove files from the algorithms directory and move them into the data structures directory

## Add new data structure Arrays in the same directory

## file names in java are conventionally written with the first letter in uppercase so they are not changed

**Review by SyedZawwarAhmed — COMMENTED** [review]
The folder structure should be as DataStructure/NameOfDataStructure/NameOfProgrammingLanguage/yourFile.

**Comment by vipul-vaishnav** [comment]
### new files added in array and linked list section of data structures

**Comment by SyedZawwarAhmed** [comment]
Thank you for the contribution, make sure to follow me.

**Pull request merged**
