### PR TITLE
added tic tac toe

### PR DESCRIPTION
**Pull request by suprakash-144**

### CODE REVIEW

**Review by SyedZawwarAhmed — COMMENTED** [review]
Change the folder name from tic tac tao to TicTacToe.

**Comment by suprakash-144** [comment]
> Change the folder name from tic tac tao to TicTacToe.

I have changed the name

**Review by SyedZawwarAhmed — COMMENTED** [review]
The folder name should be TicTacToe, not tictactoe.

**Comment by SyedZawwarAhmed** [comment]
Good work, Thanks for the contribution. You can make more pull requests to this repository.

**Pull request merged**
