### PR TITLE
Fingure Counter 🙋‍♂️🖲️👆🫰

### PR DESCRIPTION
**Pull request by kirankuyate2157**
# Fingure Counting 🖲️🙋‍♂️📸🔍

## Features
- In this project i have used Opencv and Some other liberary of python to create this amaing hand fingure counter 🤩.
- Any one can use it and for Small childs can use it for thier intresting study so they can enjoy it 👶.

<br>

image

### CODE REVIEW

**Comment by kirankuyate2157** [comment]
## hey @SyedZawwarAhmed 
 - Please check the repo and accept my PR.
 - In case anything is wrong or mistress or problem in this repo please give feedback at least 🤓

**Review by SyedZawwarAhmed — COMMENTED** [review]
Please name the project according to the CONTRIBUTING.md file.

**Comment by kirankuyate2157** [comment]
## hey @SyedZawwarAhmed 
  - I have renamed the project according to the CONTRIBUTING.md file.
  - Please check and accept my PR 🤗.

**Review by SyedZawwarAhmed — COMMENTED** [review]
remove the space from project folder name.

**Comment by kirankuyate2157** [comment]
you mean the project directory!

**Comment by kirankuyate2157** [comment]
I watched your Hotelnut project. its is amazing 🔥

**Comment by kirankuyate2157** [comment]
hey @SyedZawwarAhmed
    - I have removed space from the project folder name according to your instructions.
    - Please check and accept my PR 🤗.

**Comment by SyedZawwarAhmed** [comment]
> I watched your Hotelnut project. its is amazing 🔥

Thank you very mych.

**Comment by SyedZawwarAhmed** [comment]
Very nice project, thanks for the contribution. Make sure to follow me.

**Pull request merged**
